name: "Jason W. Gullifer, PhD"
author: "Jason W. Gullifer"
description: >
  Jason is a cognitive scientist and language scientist working at McGill University. 
  He studies the cognitive neuroscience of bilingualism and multilingualism.
keywords: bilingualism, multilingualism, bilingualism and multilingualism, bilingualism in quebec, multilingualism in quebec, bilingualism in canada, multilingualism in canada, bilingualism definition, language, linguistics, language science

url: "127.0.0.1:4000"
markdown: rdiscount
paginate: 5
plugins: [jekyll-paginate]

permalink: /blog/:categories/:year/:month/:day/:title/

collections:
  papers:
    sort_by: year
  tutorials:
    sort_by: year