name: "Jason W. Gullifer, PhD"
author: "Jason W. Gullifer"
description: >
  Jason is a cognitive scientist and language scientist working at McGill University. 
  He studies the cognitive neuroscience of bilingualism and multilingualism.

url: "127.0.0.1:4000"
keywords: bilingualism, multilingualism, bilingualism and multilingualism, bilingualism in quebec, multilingualism in quebec, bilingualism in canada, multilingualism in canada, bilingualism definition, language, linguistics, language science
paginate: 10

markdown: rdiscount
permalink: none
paginate: 5
plugins: [jekyll-paginate]